services:
  username:
    build:
      context: .
    container_name: username-service
    ports:
      - "8080:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: username-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: mongodatabase
    ports:
      - "27112:27017"
    volumes:
      - username-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: username-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgredatabase
    ports:
      - "5113:5432"
    volumes:
      - username-postgresql:/data/db/postgresql

volumes:
  username-mongodb:
    driver: local
  username-postgresql:
    driver: local
