services:
  username:
    build:
      context: .
    container_name: username-service
    ports:
      - "8080:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      mongodb:
        condition: service_healthy
      postgresql:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: username-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: mongodatabase
    ports:
      - "27112:27017"
    volumes:
      - username-mongodb:/data/db/mongodb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  postgresql:
    image: postgres:15
    container_name: username-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgredatabase
    ports:
      - "5113:5432"
    volumes:
      - username-postgresql:/data/db/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgredatabase"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  username-mongodb:
    driver: local
  username-postgresql:
    driver: local
